name: Publish
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/setup-gradle@v3
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - run: export TOKEN=${{ secrets.GITHUB_TOKEN }}
      - run: export USERNAME=${{ github.actor }}
      - run: gradle publish --no-daemon
        working-directory: ./platform-fabric-1.19.4
      - run: export -n TOKEN
        if: always()
      - run: export -n USERNAME
        if: always()