name: Publish
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd platform-fabric-1.19.4
      - uses: gradle/actions/setup-gradle@v3
      - run: export TOKEN=${{ secrets.GITHUB_TOKEN }}
      - run: export USERNAME=${{ github.actor }}
      - run: gradle publish
      - run: export -n TOKEN
        if: always()
      - run: export -n USERNAME
        if: always()